import { readFile } from 'node:fs/promises';
import {
  validateVenueGraph,
  validateVenueMetadata,
  validateVenueReachability,
} from '@indiafoss/venue';
import type { VenueGraph, VenueMetadata } from '@indiafoss/venue';

const usage = `venue-validator

Usage: venue-validator <events-dir> <event-id>

Validates events/<event-id>/venue/{venue.svg, venue.graph.json, venue.metadata.json}
against the §53 checklist and prints a human-readable report.
`;

export interface ValidationReport {
  eventId: string;
  graphIssues: string[];
  metadataIssues: string[];
  reachabilityIssues: string[];
  svgTargetIssues: string[];
  /** svgTargets referenced by metadata but missing from the SVG. */
  missingSvgTargets: string[];
}

/**
 * Derive the venue's public origin(s) for reachability: the entrance node(s)
 * of any location whose id names it (registration / entrance / reception),
 * falling back to a bare `entrance` graph node when present.
 */
function originEntrances(metadata: VenueMetadata, graph: VenueGraph): string[] {
  const origins = new Set<string>();
  for (const [locationId, ref] of Object.entries(metadata.locations)) {
    if (/registration|entrance|reception|lobby/i.test(locationId)) {
      for (const e of ref.entrances) origins.add(e);
    }
  }
  if (origins.size === 0 && graph.nodes.some((n) => n.id === 'entrance')) {
    origins.add('entrance');
  }
  return [...origins];
}

export async function validateVenue(eventDir: string, eventId: string): Promise<ValidationReport> {
  const base = `${eventDir}/${eventId}/venue`;
  const graph = JSON.parse(await readFile(`${base}/venue.graph.json`, 'utf8')) as VenueGraph;
  const metadata = JSON.parse(
    await readFile(`${base}/venue.metadata.json`, 'utf8'),
  ) as VenueMetadata;
  const svg = await readFile(`${base}/venue.svg`, 'utf8');

  const graphIssues = validateVenueGraph(graph);
  const metadataIssues = validateVenueMetadata(metadata, graph);
  const reachabilityIssues = validateVenueReachability(
    graph,
    metadata,
    originEntrances(metadata, graph),
  );

  const svgIds = new Set([...svg.matchAll(/id="([^"]+)"/g)].map((m) => m[1]!));
  const missingSvgTargets: string[] = [];
  for (const ref of Object.values(metadata.locations)) {
    if (ref.svgTarget && !svgIds.has(ref.svgTarget)) {
      missingSvgTargets.push(`${ref.locationId} -> #${ref.svgTarget}`);
    }
  }

  return {
    eventId,
    graphIssues,
    metadataIssues,
    reachabilityIssues,
    svgTargetIssues: [],
    missingSvgTargets,
  };
}

export function formatReport(report: ValidationReport): string {
  const lines: string[] = [`venue validation report — ${report.eventId}`];
  const sections: [string, string[]][] = [
    ['graph', report.graphIssues],
    ['metadata', report.metadataIssues],
    ['reachability', report.reachabilityIssues],
    ['svg targets', report.missingSvgTargets.map((m) => `missing ${m}`)],
  ];
  let problems = 0;
  for (const [name, issues] of sections) {
    if (issues.length === 0) {
      lines.push(`  ✓ ${name}: ok`);
    } else {
      problems += issues.length;
      lines.push(`  ✗ ${name}:`);
      for (const issue of issues) lines.push(`      - ${issue}`);
    }
  }
  lines.push(
    problems === 0
      ? 'RESULT: PASS'
      : `RESULT: FAIL (${problems} problem${problems === 1 ? '' : 's'})`,
  );
  return lines.join('\n');
}

/** Render the report as a committable Markdown document. */
export function formatReportMarkdown(report: ValidationReport): string {
  const problems =
    report.graphIssues.length +
    report.metadataIssues.length +
    report.reachabilityIssues.length +
    report.missingSvgTargets.length;
  const lines: string[] = [
    `# Venue validation report — ${report.eventId}`,
    '',
    `**Result:** ${problems === 0 ? '✅ PASS' : `❌ FAIL (${problems} problem${problems === 1 ? '' : 's'})`}`,
    '',
    '_Generated by `just venue-report`. Structural checks only — the physical',
    'floor plan is the source of truth; see the route-review checklist._',
    '',
  ];
  const sections: [string, string, string[]][] = [
    [
      'Graph',
      'Duplicate ids, dangling edges, negative/zero weights, self-loops.',
      report.graphIssues,
    ],
    [
      'Metadata',
      'Entrances exist; declared floor matches entrance-node floor.',
      report.metadataIssues,
    ],
    [
      'Reachability & floors',
      'Every public location reachable from the entrance; floor changes only via stairs/lift.',
      report.reachabilityIssues,
    ],
    [
      'SVG targets',
      'Every metadata svgTarget resolves to an element in venue.svg.',
      report.missingSvgTargets.map((m) => `missing ${m}`),
    ],
  ];
  for (const [name, desc, issues] of sections) {
    lines.push(`## ${name}`, '', `_${desc}_`, '');
    if (issues.length === 0) {
      lines.push('- ✅ ok');
    } else {
      for (const issue of issues) lines.push(`- ❌ ${issue}`);
    }
    lines.push('');
  }
  return lines.join('\n');
}

export async function main(): Promise<void> {
  const args = process.argv.slice(2);
  const markdown = args.includes('--markdown');
  const positional = args.filter((a) => !a.startsWith('--'));
  const [eventsDir, eventId] = positional;
  if (!eventsDir || !eventId) {
    console.error(usage);
    process.exitCode = 1;
    return;
  }
  const report = await validateVenue(eventsDir, eventId);
  console.log(markdown ? formatReportMarkdown(report) : formatReport(report));
  const problems =
    report.graphIssues.length +
    report.metadataIssues.length +
    report.reachabilityIssues.length +
    report.missingSvgTargets.length;
  process.exitCode = problems === 0 ? 0 : 1;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  void main();
}
