/**
 * EventManifest — what a client fetches to discover whether the event data it
 * already holds is still current, and which immutable assets make up the
 * current revision.
 *
 * The manifest is the *pointer*; {@link import('../index.js').EventBundle} is
 * the data. They version independently: a manifest format change must not
 * force a bundle republish, and vice versa.
 *
 * This type already exists on disk — `events/<eventId>/published/manifest.json`
 * is generated by `tools/event-sync`. This module is the owning definition;
 * the tool should import from here rather than redeclaring it.
 *
 * See ADR 0009 and `docs/architecture/system.md` ("Share contracts").
 */
import {
  collectSchemaVersionIssues,
  isRecord,
  optionalInstant,
  optionalString,
  requireInstant,
  requireString,
} from './common.js';

/** Current manifest format. Independent of `EVENT_BUNDLE_SCHEMA_VERSION`. */
export const EVENT_MANIFEST_SCHEMA_VERSION = 1;

export interface EventManifest {
  /** Manifest format version. See {@link EVENT_MANIFEST_SCHEMA_VERSION}. */
  schemaVersion: number;
  /** Stable event identifier, e.g. `indiafoss-2026`. Never reused across years. */
  eventId: string;
  /**
   * Monotonic revision. Increments only when published content actually
   * changes; a re-sync producing identical content keeps the revision, so a
   * client can treat "same revision" as "nothing to apply".
   */
  revision: number;
  /** When this manifest was generated, ISO-8601. */
  generatedAt: string;
  /** Upstream's own last-modified marker, when the source provides one. */
  sourceUpdatedAt?: string;
  /**
   * Asset filenames by role, each carrying an 8-hex content digest
   * (`event.683f9fc4.json`). Digests make assets immutable and safely
   * cacheable; they detect corruption, not authorship. Authenticity rests on
   * the controlled HTTPS origin — if bundles ever travel through untrusted
   * peers, this contract needs signed manifests and a pinned publisher key
   * before that is safe.
   */
  assets: Record<string, string>;
  /**
   * IANA timezone the event's local times are expressed in. Optional for
   * compatibility with already-published manifests; new publishes should set
   * it so a client can render local times before fetching the bundle.
   */
  timezone?: string;
  /**
   * Digest over the normalized bundle this revision publishes, when the
   * publisher computes one. Lets a client verify a bundle it fetched
   * separately belongs to this revision.
   */
  bundleDigest?: string;
}

const ASSET_FILENAME = /^[A-Za-z0-9._-]+$/;

/**
 * Structural validation for an untrusted manifest.
 *
 * An empty list means the manifest is structurally usable. It does **not**
 * mean the assets exist, that their digests match, or that the publisher is
 * who you think — see the note on {@link EventManifest.assets}.
 */
export function collectEventManifestIssues(value: unknown): string[] {
  if (!isRecord(value)) return ['manifest must be an object'];
  const issues: string[] = [
    ...collectSchemaVersionIssues(value, EVENT_MANIFEST_SCHEMA_VERSION, 'manifest'),
    ...requireString(value, 'eventId'),
    ...requireInstant(value, 'generatedAt'),
    ...optionalInstant(value, 'sourceUpdatedAt'),
    ...optionalString(value, 'timezone'),
    ...optionalString(value, 'bundleDigest'),
  ];

  const { revision } = value;
  if (typeof revision !== 'number' || !Number.isInteger(revision) || revision < 1) {
    issues.push(`revision must be a positive integer, got ${JSON.stringify(revision)}`);
  }

  if (!isRecord(value.assets)) {
    issues.push('assets must be an object mapping role to filename');
  } else {
    const entries = Object.entries(value.assets);
    if (entries.length === 0) issues.push('assets must not be empty');
    for (const [role, filename] of entries) {
      if (typeof filename !== 'string' || !filename.trim()) {
        issues.push(`assets.${role} must be a non-empty filename`);
      } else if (!ASSET_FILENAME.test(filename)) {
        // A path separator here would let a manifest point outside the
        // published directory.
        issues.push(`assets.${role} must be a plain filename, got ${JSON.stringify(filename)}`);
      }
    }
  }

  return issues;
}

/** True when the manifest passes structural checks. */
export function isValidEventManifest(value: unknown): value is EventManifest {
  return collectEventManifestIssues(value).length === 0;
}

/**
 * Whether `candidate` should replace `current`.
 *
 * Applies only to the same `eventId`, and only forwards. A manifest fetched
 * from a stale cache or a replayed response must never roll a client back.
 */
export function supersedes(candidate: EventManifest, current: EventManifest | undefined): boolean {
  if (!current) return true;
  if (candidate.eventId !== current.eventId) return false;
  return candidate.revision > current.revision;
}
